lint:
  files_unchanged:
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - config_defaults:
        - params.phix_reference
        - params.lambda_reference
nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: "Hadrien Gourlé, Daniel Straub, Sabrina Krakau, James A. Fellows Yates, Maxime Borry"
  description: Assembly, binning and annotation of metagenomes
  force: false
  is_nfcore: true
  name: mag
  org: nf-core
  outdir: .
  version: 3.3.0dev
