# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "shortread_assembly"
description: Short-read genome assembly using SPAdes and MEGAHIT
keywords:
  - assembly
  - short reads
  - metagenomics
  - spades
  - megahit
components:
  - spades
  - megahit
input:
  - ch_short_reads_grouped:
      description: Grouped short-read data
      structure:
        - meta:
            type: map
            description: Metadata map
        - fastq1:
            type: file
            description: First pair of short-read FASTQ files
            pattern: "*.{fastq,fq}.gz"
        - fastq2:
            type: file
            description: Second pair of short-read FASTQ files
            pattern: "*.{fastq,fq}.gz"
  - ch_short_reads_spades:
      description: Short-read data prepared for SPAdes
      structure:
        - meta:
            type: map
            description: Metadata map
        - reads:
            type: file
            description: Short-read FASTQ files (array)
            pattern: "*.{fastq,fq}.gz"
output:
  - assembled_contigs:
      description: Assembled contigs
      structure:
        - meta:
            type: map
            description: Metadata map
        - fasta:
            type: file
            description: Assembled contigs in FASTA format
            pattern: "*.fasta.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@muabnezor"
maintainers:
  - "@jfy133"
  - "@prototaxites"
  - "@dialvarezs"
  - "@d4straub"
  - "@muabnezor"
