# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bigmag"
description: Executing alternative tools to complete the required input file for BIgMAG dashboard
keywords:
  - quality control
  - bins
  - metagenomics
  - busco
  - checkm2
  - gunc
components:
  - busco/busco
  - checkm2/databasedownload
  - checkm2/predict
  - concat/bigmag
  - bigmag/summary
  - gunc/downloaddb
  - gunc/run
  - untar
input:
  - ch_bins:
      description: Metagenomic bins in FASTA format
      structure:
        - meta:
            type: map
            description: Metadata map
        - fasta:
            type: file
            description: Metagenomic bins in FASTA format
            pattern: "*.{fasta,fa}"
  - summary:
      description: Bin summary
      structure:
        - meta:
            type: map
            description: Metadata map
        - fasta:
            type: file
            description: Bin summary as TSV file
            pattern: "*.tsv"
output:
  - bigmag_summary:
      description: Combined quality assessment summary
      structure:
        - meta:
            type: map
            description: Metadata map
        - tsv:
            type: file
            description: Summary in TSV format ready to be used for BIgMAG
            pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - multiqc_files:
      description: MultiQC files for quality control statistics
      structure:
        - meta:
            type: map
            description: Metadata map
        - "*":
            type: file
            description: MultiQC report files
            pattern: "*"
authors:
  - "@jeffe107"
maintainers:
  - "@jfy133"
  - "@prototaxites"
  - "@dialvarezs"
  - "@d4straub"
  - "@muabnezor"
