# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "longread_hostremoval"
description: Host genome contamination removal from long-read sequencing data
keywords:
  - host removal
  - contamination
  - long reads
  - nanopore
  - pacbio
components:
  - minimap2/index
  - minimap2/align
  - samtools/index
  - samtools/stats
  - samtools/unmapped
input:
  - ch_reads:
      description: Long-read sequencing data
      structure:
        - meta:
            type: map
            description: Metadata map
        - reads:
            type: file
            description: Long-read FASTQ files
            pattern: "*.{fastq,fq}.gz"
  - val_reference:
      type: val
      description: Path to host genome reference
output:
  - stats:
      description: Alignment statistics
      structure:
        - meta:
            type: map
            description: Metadata map
        - stats:
            type: file
            description: Alignment statistics files
            pattern: "*.txt"
  - reads:
      description: Host-removed long reads
      structure:
        - meta:
            type: map
            description: Metadata map
        - fastq:
            type: file
            description: Host-removed long-read FASTQ files
            pattern: "*.{fastq,fq}.gz"
  - multiqc_files:
      description: MultiQC files for statistics
      structure:
        - meta:
            type: map
            description: Metadata map
        - "*":
            type: file
            description: MultiQC report files
            pattern: "*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@muabnezor"
maintainers:
  - "@jfy133"
  - "@prototaxites"
  - "@dialvarezs"
  - "@d4straub"
  - "@muabnezor"
