---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.9
  - conda-forge::pandas=1.3.0
  - conda-forge::seaborn=0.11.0
  - conda-forge::matplotlib=3.4.2
