# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "domain_classification"
description: Domain-level classification of metagenomic sequences using Tiara and other tools
keywords:
  - domain classification
  - metagenomics
  - tiara
  - prokaryote
  - eukaryote
components:
  - tiara
input:
  - ch_assemblies:
      description: Assembled contigs
      structure:
        - meta:
            type: map
            description: Metadata map
        - assembly:
            type: file
            description: Assembled contigs in FASTA format
            pattern: "*.{fasta,fa}"
  - ch_bins:
      description: Metagenomic bins
      structure:
        - meta:
            type: map
            description: Metadata map
        - bins:
            type: file
            description: Metagenomic bins in FASTA format
            pattern: "*.{fasta,fa}"
  - ch_unbins:
      description: Unbinned contigs
      structure:
        - meta:
            type: map
            description: Metadata map
        - unbins:
            type: file
            description: Unbinned contigs in FASTA format
            pattern: "*.{fasta,fa}"
output:
  - classified_bins:
      description: Domain-classified bins
      structure:
        - meta:
            type: map
            description: Metadata map with domain information
        - bins:
            type: file
            description: Domain-classified bins
            pattern: "*.{fasta,fa}"
  - classified_unbins:
      description: Domain-classified unbinned contigs
      structure:
        - meta:
            type: map
            description: Metadata map with domain information
        - unbins:
            type: file
            description: Domain-classified unbinned contigs
            pattern: "*.{fasta,fa}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@prototaxites"
maintainers:
  - "@jfy133"
  - "@prototaxites"
  - "@dialvarezs"
  - "@d4straub"
  - "@muabnezor"
